direct:
  local_map_res: 0.1
  local_map_update_alpha: 0.1
  max_local_map_range: 150.0
  max_range: 70.0
  min_range: 4.0
doppler:
  max_range: 200.0
  min_range: 4.0
estimation:
  T_axle_radar:
  - - 0.99938287
    - 0.03512667
    - 0.0
    - 0.51
  - - 0.03512667
    - -0.99938287
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - -1.0
    - 1.945
  - - 0.0
    - 0.0
    - 0.0
    - 1.0
  estimate_vy_bias: true
  estimate_gyro_bias: false
  use_gyro: true
  vy_bias_prior: 0.11
  min_time_bias_init: 1.0
  gyro_bias_alpha: 0.01
  max_acceleration: 10.0
gp:
  lengthscale_az: 2.0
  lengthscale_range: 4.0
  sz: 0.6
log:
  display: false
  save_images: false
  save_local_maps: false
  verbose: true
  save_scans: false
  max_scan_range: 120.0
radar:
  beta_corr_fact: 0.944
  del_f: 893.0E6
  ft: 76.04E9
  meas_freq: 1600.0
  range_offset: -0.31
  resolution: 0.04381
  doppler_enabled: true
  nb_azimuths: 400
solver:
  nb_iter: 25
  cost_tol: 1.0E-3
  step_tol: 1.0E-3
